services:
  - type: web
    name: football-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements_simple.txt
    startCommand: gunicorn test_app:app -k uvicorn.workers.UvicornWorker
